[project]
name = "global"
version = "1.0.0"
description = "Global PIP Staging."
authors = [{ name = "Ãlan CrÃ­stoffer", email = "acristoffers@startmail.com" }]
requires-python = ">=3.11"
dependencies = [
    "dictor>=0.1.12",
    "hererocks>=0.25.1",
    "pip>=26.0.1",
    "pycode-similar>=1.4",
    "uv-bump>=0.4.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
